import type { Metadata } from 'next'
import { ChakraProvider } from '@chakra-ui/react'
import { Poppins, Roboto } from 'next/font/google'

import './globals.css'

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-poppins',
})

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: 'ui-commerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={`${poppins.variable} ${roboto.variable}`}>
      <body className="font-sans">
        <ChakraProvider>{children}</ChakraProvider>
      </body>
    </html>
  )
}
